service: drive-auth

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  profile: driver
  runtime: nodejs10.x
  stage: dev
  region: eu-central-1
  memorySize: 256

package:
  exclude:
    - '**/*.ts'
    
functions:
  signup:
    handler: handlers/signup.signup
    events:
      - http:
          path: signup
          method: post
          