swagger: "2.0"
info:
  title: "Drive Auth Service"
  description: "https://4p1q9ue43m.execute-api.eu-central-1.amazonaws.com/test"
  version: "1.0.0"
basePath: "/"
schemes:
- "https"
paths:
  /signup:
    post:
      summary: "Sign up"
      operationId: "signUp"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/SignUpDetails"
      responses:
        401:
          description: "Unauthorized"
          schema:
            $ref: '#/definitions/ErrorResponse'
        200:
          description: "Successful sign-up"
          schema:
            properties: {}
  /signin:
    post:
      summary: "Sign in"
      operationId: "signIn"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/AuthenticationCredentials"
      responses:
        401:
          description: "Unauthorized"
          schema:
            $ref: '#/definitions/ErrorResponse'
        200:
          description: "Successful authentication response containing access/refresh token to be saved on the client's end"
          schema:
            $ref: '#/definitions/AuthenticatedResponse'
definitions:
  SignUpDetails:
    type: object
    required:
      - email
      - password
      - given_name
      - family_name
      - phone_number
    properties:
      email:
        type: string
        example: "weinberger.ariel@gmail.com"
      password:
        type: string
        example: "sup3rP4ssw0rd"
      given_name:
        type: string
        example: "Ariel"
      family_name:
        type: string
        example: "Weinberger"
      phone_number:
        type: string
        example: "+31615565542"
        
  AuthenticationCredentials:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        description: "Email used to sign up"
      password:
        type: string
        description: "Password used to sign up"
    
  ErrorResponse:
    type: "object"
    properties:
      code:
        type: "string"
        description: "AWS Cognito code describing what went wrong"
        example: "UserNotFoundException"
      message:
        type: "string"
        example: "User does not exist."
        
  AuthenticatedResponse:
    type: "object"
    properties:
      TokenType:
        type: string
        example: "Bearer"
      AccessToken:
        type: string
        example: "jwt"
      RefreshToken:
        type: string
        example: "jwt"
      ExpiresIn:
        type: number
        example: 3600
        